# -*- coding: utf-8 -*-

labels = {
    "acao_orcamentaria": u"Ação Orçamentária",
    "agencia_bancaria": u"Agência bancária",
    "associacao": u"Associação",
    "atende_a": u"Atende a",
    "capacidade_tecnica": u"Capacidade técnica",
    "cep": u"CEP",
    "cnpj": u"CNPJ",
    "cod_programa_siconv": u"Cód. do Programa no SICONV",
    "cod_siasg": u"Cód. no SIASG",
    "codigo_banco": u"Código do banco",
    "composicao_repasse": u"Composição do Repasse",
    "conta_bancaria": u"Conta bancária",
    "contrapartida": u"Contrapartida total",
    "contrapartida_bens_servicos": u"Contrapartida em bens e serviços",
    "CONTRATO DE REPASSE": u"Contrato de Repasse",
    "convenio": u"Convenio",
    "Convenio": u"Convênio",
    "CONVENIO": u"Convênio", # modalidade
    "convenios": u"Convênios",
    "cpf": u"CPF",
    "cpf_pessoa_responsavel_pelo_cadastramento": u"CPF da pessoa responsável pelo cadastramento",
    "cpf_pessoa_responsavel_pelo_concedente": u"CPF da pessoa responsável pelo concedente",
    "cpf_pessoa_responsavel_pelo_envio": u"CPF da pessoa responsável pelo envio",
    "cpf_responsavel": u"CPF do responsável",
    "data_assinatura": u"Data de assinatura",
    "data_ateste": u"Data de ateste",
    "data_disponibilizacao": u"Data de disponibilização",
    "data_emissao": u"Data de emissão",
    "data_fim_vigencia": u"Data de fim de vigência",
    "data_inicio_recebimento_propostas": u"Data de início de recebimento de propostas",
    "data_inicio_vigencia": u"Data de início de vigência",
    "data_publicacao": u"Data de publicação",
    "descricao": u"Descrição",
    "descricao_natureza_despesa_subitem": u"Descrição do subitem da nautreza de despesa",
    "doc_uri": u"URI da documentação",
    "endereco": u"Endereço",
    "esfera_orcamentaria": u"Esfera Orçamentária",
    "HabilitacaoAreaAtuacao": u"Habilitação em Área de Atuação",
    "identificacao": u"Identificação",
    "natureza_despesa_subitem": u"Subitem da natureza de despesa",
    "natureza_juridica": u"Natureza jurídica",
    "nome_responsavel": u"Nome do responsável",
    "numero": u"Número",
    "numero_documento_habil_siafi": u"Número do documento hábil no SIAFI",
    "numero_lista": u"Número de lista",
    "numero_natureza_despesa_subitem": u"Número do subitem da nautreza de despesa",
    "numero_plano_interno": u"Número do plano interno",
    "numero_plano_trabalho_resumido": u"Número do plano de trabalho resumido",
    "numero_processo": u"Número do processo",
    "numero_interno": u"Número interno",
    "observacao": u"Observação",
    "Orgao": u"Órgão",
    "orgao_concedente": u"Órgão concedente",
    "orgao_executor": u"Órgão executor",
    "orgao_mandatario": u"Órgão mandatário",
    "orgao_superior": u"Órgão superior",
    "orgao_vinculado": u"Órgão vinculado",
    "orgaos": u"Órgãos",
    "parametros": u"Parâmetros",
    "PessoaResponsavel": u"Pessoa Responsável",
    "pessoas_responsaveis": u"Pessoas Responsáveis",
    "propostas_como_responsavel": u"Propostas como responsável",
    "regiao": u"Região",
    "repasse": u"Repasse da União",
    "situacao": u"Situação",
    "situacao_publicacao": u"Situação de publicação",
    "SituacaoConvenio": u"Situação de Convênio",
    "SubsituacaoConvenio": u"Subsituação de Convênio",
    "SituacaoProposta": u"Situação de Proposta",
    "SituacaoPublicacao": u"Situação de Publicação",
    "SituacaoPublicacaoConvenio": u"Situação de Publicação de Convênio",
    "subsituacao": u"Subsituação",
    "uri": u"URI",
    "valor_contra_partida": u"Valor da contrapartida",
    "valor_contrapartida_bens_servicos": u"Contrapartida em bens e serviços",
    "valor_contrapartida_financeira": u"Contrapartida financeira",
    "valor_global": u"Global",
    "valor_repasse": u"Repasse da União",
    "vinculacao": u"Vinculação",
}